// Single-character glosses for hanzi that appear in the app (inside words,
// sentences, grammar examples, and IDS components) but aren't standalone HSK
// vocabulary entries. Format: 'pinyin|short learner-facing meaning'.
// Radical-only forms (亻, 氵, 扌…) are labelled as such.

export const charGlosses: Record<string, string> = {
  丁: 'dīng|nail; small cube; fourth in a series',
  丈: 'zhàng|ten feet (unit); husband',
  专: 'zhuān|special; focused',
  且: 'qiě|moreover; and',
  世: 'shì|world; generation; lifetime',
  业: 'yè|business; industry; course of study',
  严: 'yán|strict; severe',
  丨: 'gǔn|vertical stroke (radical)',
  丩: 'jiū|entangled (component)',
  中: 'zhōng|middle; China',
  丰: 'fēng|abundant; plentiful',
  丶: 'zhǔ|dot (radical)',
  主: 'zhǔ|master; main; to host',
  丽: 'lì|beautiful',
  乃: 'nǎi|to be; thus (literary)',
  么: 'me|suffix in 什么 / 怎么',
  义: 'yì|justice; meaning',
  乍: 'zhà|suddenly; at first',
  乎: 'hū|classical particle',
  乐: 'lè / yuè|happy / music',
  乒: 'pīng|"ping" of ping-pong',
  乓: 'pāng|"pong" of ping-pong',
  乔: 'qiáo|tall',
  乘: 'chéng|to ride; to multiply',
  乞: 'qǐ|to beg',
  习: 'xí|to practice; habit',
  予: 'yǔ|to give',
  争: 'zhēng|to compete; to argue',
  事: 'shì|matter; thing; affair',
  于: 'yú|at; in; to (preposition)',
  互: 'hù|mutual; each other',
  井: 'jǐng|a well',
  亚: 'yà|second; Asia',
  亡: 'wáng|to die; to flee',
  亥: 'hài|twelfth Earthly Branch',
  亦: 'yì|also (literary)',
  京: 'jīng|capital city',
  亭: 'tíng|pavilion',
  亮: 'liàng|bright',
  亲: 'qīn|relative; dear; to kiss',
  亻: 'rén|person — side form of 人 (radical)',
  什: 'shén|what (in 什么)',
  仅: 'jǐn|only; merely',
  今: 'jīn|now; today',
  介: 'jiè|to lie between; to introduce',
  仍: 'réng|still; yet',
  仑: 'lún|order; arrangement (component)',
  仔: 'zǐ|careful; young (animal)',
  付: 'fù|to pay; to hand over',
  代: 'dài|to replace; generation; era',
  令: 'lìng|order; command',
  们: 'men|plural suffix for people',
  价: 'jià|price; value',
  任: 'rèn|to appoint; any; duty',
  休: 'xiū|to rest',
  众: 'zhòng|crowd; many people',
  优: 'yōu|excellent',
  伙: 'huǒ|companion; partner',
  传: 'chuán|to pass on; to spread',
  伤: 'shāng|injury; to hurt',
  估: 'gū|to estimate',
  但: 'dàn|but; only',
  体: 'tǐ|body; form',
  何: 'hé|what; how (literary)',
  余: 'yú|surplus; remaining',
  作: 'zuò|to do; to make; to write',
  佥: 'qiān|all (component)',
  佰: 'bǎi|hundred (formal/financial)',
  例: 'lì|example',
  供: 'gōng|to supply; to provide',
  依: 'yī|to depend on; according to',
  便: 'biàn / pián|convenient / cheap (便宜)',
  保: 'bǎo|to protect; to keep',
  俞: 'yú|surname Yu (component)',
  信: 'xìn|letter; to believe; trust',
  俩: 'liǎ|two people; both',
  修: 'xiū|to repair; to study',
  候: 'hòu|to wait; season; time',
  值: 'zhí|value; to be worth',
  健: 'jiàn|healthy; strong',
  偶: 'ǒu|by chance; even number; idol',
  偷: 'tōu|to steal',
  傅: 'fù|tutor; master (in 师傅)',
  傍: 'bàng|near; approaching (傍晚 dusk)',
  傲: 'ào|proud; arrogant',
  儿: 'ér|son; child; -r suffix',
  允: 'yǔn|to allow',
  兄: 'xiōng|elder brother',
  充: 'chōng|to fill; full',
  兆: 'zhào|omen; million',
  克: 'kè|gram; to overcome',
  免: 'miǎn|to avoid; exempt',
  兑: 'duì|to exchange',
  入: 'rù|to enter',
  全: 'quán|whole; all',
  公: 'gōng|public; male (animal)',
  兰: 'lán|orchid',
  共: 'gòng|together; common',
  兴: 'xìng / xīng|interest / to rise',
  其: 'qí|his; her; its; that',
  具: 'jù|tool; to possess',
  典: 'diǎn|classic; standard; ceremony',
  养: 'yǎng|to raise; to keep (pets)',
  冂: 'jiōng|borders (radical)',
  冒: 'mào|to emit; to risk',
  冗: 'rǒng|superfluous',
  冠: 'guān / guàn|hat / champion',
  冫: 'bīng|ice — side form (radical)',
  冰: 'bīng|ice',
  决: 'jué|to decide',
  况: 'kuàng|situation; moreover',
  净: 'jìng|clean; net',
  准: 'zhǔn|accurate; to allow',
  凉: 'liáng|cool; cold',
  减: 'jiǎn|to reduce; to subtract',
  凡: 'fán|ordinary; every',
  击: 'jī|to hit; to strike',
  切: 'qiē / qiè|to cut / close to',
  划: 'huá / huà|to row / to plan; stroke',
  列: 'liè|row; to list',
  则: 'zé|rule; then',
  判: 'pàn|to judge',
  利: 'lì|profit; sharp; benefit',
  刮: 'guā|to scrape; (wind) to blow',
  刷: 'shuā|brush; to brush',
  前: 'qián|front; before',
  剧: 'jù|drama; play',
  力: 'lì|strength; power',
  办: 'bàn|to do; to handle',
  功: 'gōng|merit; achievement',
  加: 'jiā|to add; plus',
  务: 'wù|affair; business',
  动: 'dòng|to move',
  助: 'zhù|to help',
  努: 'nǔ|to exert effort',
  励: 'lì|to encourage',
  劳: 'láo|labor; to toil',
  勇: 'yǒng|brave',
  勺: 'sháo|spoon; ladle',
  勿: 'wù|do not',
  匕: 'bǐ|dagger; spoon (radical)',
  化: 'huà|to change; -ize',
  北: 'běi|north',
  匙: 'chí / shi|spoon / key (in 钥匙)',
  区: 'qū|area; district',
  医: 'yī|doctor; medicine',
  升: 'shēng|to rise; liter',
  午: 'wǔ|noon',
  卓: 'zhuó|outstanding; tall',
  单: 'dān|single; list; sheet',
  博: 'bó|extensive; to gain',
  占: 'zhàn|to occupy; to take up',
  卡: 'kǎ|card',
  卫: 'wèi|to guard; hygiene',
  卯: 'mǎo|fourth Earthly Branch',
  印: 'yìn|to print; seal; stamp',
  危: 'wēi|danger',
  即: 'jí|namely; immediately',
  厅: 'tīng|hall; living room',
  历: 'lì|to experience; calendar; history',
  厉: 'lì|severe; strict',
  压: 'yā|to press; pressure',
  厌: 'yàn|to dislike; tired of',
  厕: 'cè|toilet',
  原: 'yuán|original; source',
  厨: 'chú|kitchen',
  厶: 'sī|private (radical)',
  参: 'cān|to take part in',
  及: 'jí|and; to reach',
  友: 'yǒu|friend',
  反: 'fǎn|opposite; to reverse',
  发: 'fā / fà|to send; to issue / hair (头发)',
  叔: 'shū|uncle',
  受: 'shòu|to receive; to bear',
  变: 'biàn|to change',
  叚: 'jiǎ|to borrow (component)',
  古: 'gǔ|ancient',
  句: 'jù|sentence; measure word for phrases',
  另: 'lìng|other; another',
  召: 'zhào|to summon',
  可: 'kě|can; may',
  史: 'shǐ|history',
  右: 'yòu|right (side)',
  叶: 'yè|leaf',
  司: 'sī|to manage; department',
  吅: 'xuān|clamor (component)',
  合: 'hé|to combine; to close; together',
  同: 'tóng|same; together',
  名: 'míng|name; famous',
  后: 'hòu|behind; after',
  否: 'fǒu|not; no',
  吧: 'ba|suggestion particle',
  含: 'hán|to contain; to hold in the mouth',
  吸: 'xī|to inhale; to attract',
  吾: 'wú|I; me (literary)',
  呆: 'dāi|dull; to stay',
  告: 'gào|to tell; to report',
  员: 'yuán|member; staff',
  周: 'zhōu|week; circuit; around',
  味: 'wèi|taste; flavor',
  呼: 'hū|to call; to breathe out',
  命: 'mìng|life; fate; order',
  咅: 'pǒu|to spit (component)',
  咖: 'kā|"ka" in 咖啡 coffee',
  咬: 'yǎo|to bite',
  咱: 'zán|we (including you)',
  咳: 'ké|to cough',
  哈: 'hā|ha (laughter)',
  哥: 'gē|elder brother',
  售: 'shòu|to sell',
  唯: 'wéi|only',
  唱: 'chàng|to sing',
  商: 'shāng|commerce; to discuss',
  啡: 'fēi|"fei" in 咖啡 coffee',
  啤: 'pí|"pi" in 啤酒 beer',
  喜: 'xǐ|to like; happy',
  嗽: 'sòu|to cough (in 咳嗽)',
  囗: 'wéi|enclosure (radical)',
  因: 'yīn|cause; because',
  团: 'tuán|group; ball',
  园: 'yuán|garden; park',
  围: 'wéi|to surround',
  国: 'guó|country',
  图: 'tú|picture; map; to plan',
  土: 'tǔ|earth; soil',
  圭: 'guī|jade tablet (component)',
  地: 'dì|ground; place; earth',
  圾: 'jī|"ji" in 垃圾 garbage',
  址: 'zhǐ|site; address',
  坚: 'jiān|firm; solid',
  垂: 'chuí|to hang down',
  垃: 'lā|"la" in 垃圾 garbage',
  城: 'chéng|city; city wall',
  基: 'jī|base; foundation',
  堇: 'jǐn|clay (component)',
  堵: 'dǔ|to block',
  塑: 'sù|to mold; plastic (塑料)',
  填: 'tián|to fill in',
  境: 'jìng|border; environment',
  增: 'zēng|to increase',
  士: 'shì|scholar; soldier',
  声: 'shēng|sound; voice',
  壶: 'hú|pot; kettle',
  处: 'chù / chǔ|place / to deal with',
  备: 'bèi|to prepare',
  复: 'fù|to repeat; to reply',
  天: 'tiān|sky; day',
  夫: 'fū|husband; man',
  夬: 'guài|to decide (component)',
  央: 'yāng|center',
  失: 'shī|to lose',
  头: 'tóu|head',
  夹: 'jiā|to clip; to squeeze',
  奇: 'qí|strange; odd',
  奋: 'fèn|to exert oneself',
  奖: 'jiǎng|prize; award',
  奴: 'nú|slave',
  奶: 'nǎi|milk; grandma',
  如: 'rú|as; like; if',
  妈: 'mā|mom',
  妹: 'mèi|younger sister',
  妻: 'qī|wife',
  妾: 'qiè|concubine (component)',
  始: 'shǐ|to begin',
  姐: 'jiě|older sister',
  姥: 'lǎo|grandma (maternal)',
  姨: 'yí|aunt (mother’s sister)',
  娄: 'lóu|(component; surname Lou)',
  娘: 'niáng|mother; young woman',
  婆: 'pó|old woman; mother-in-law',
  婚: 'hūn|marriage',
  嫁: 'jià|(of a woman) to marry',
  子: 'zǐ|child; son; noun suffix',
  孙: 'sūn|grandson',
  季: 'jì|season',
  孤: 'gū|lonely; orphan',
  学: 'xué|to study',
  孩: 'hái|child',
  宀: 'mián|roof (radical)',
  宁: 'níng|peaceful',
  安: 'ān|safe; calm',
  官: 'guān|official',
  定: 'dìng|to fix; to decide; certain',
  宜: 'yí|suitable',
  实: 'shí|real; solid',
  客: 'kè|guest; customer',
  室: 'shì|room',
  害: 'hài|harm; to harm',
  容: 'róng|to contain; appearance',
  宽: 'kuān|wide',
  宾: 'bīn|guest',
  宿: 'sù|to stay overnight',
  寅: 'yín|third Earthly Branch',
  密: 'mì|secret; dense',
  寒: 'hán|cold',
  察: 'chá|to examine',
  寸: 'cùn|inch; thumb',
  寺: 'sì|temple',
  导: 'dǎo|to guide; to lead',
  封: 'fēng|to seal; envelope',
  射: 'shè|to shoot',
  将: 'jiāng|will; shall',
  尊: 'zūn|to respect',
  尔: 'ěr|you (literary); so',
  尖: 'jiān|sharp; pointed',
  尚: 'shàng|still; to value',
  尤: 'yóu|especially',
  尧: 'yáo|Emperor Yao (component)',
  尸: 'shī|corpse (radical)',
  尼: 'ní|nun',
  尽: 'jìn|to exhaust; utmost',
  尿: 'niào|urine',
  局: 'jú|office; situation; game',
  居: 'jū|to reside',
  屈: 'qū|to bend; grievance',
  屋: 'wū|house; room',
  展: 'zhǎn|to unfold; exhibition',
  山: 'shān|mountain',
  岛: 'dǎo|island',
  岸: 'àn|shore; bank',
  峰: 'fēng|peak',
  川: 'chuān|river',
  州: 'zhōu|state; prefecture',
  巠: 'jīng|underground stream (component)',
  工: 'gōng|work',
  左: 'zuǒ|left',
  巧: 'qiǎo|skillful; coincidental',
  巨: 'jù|huge',
  巩: 'gǒng|firm; to consolidate',
  己: 'jǐ|self',
  已: 'yǐ|already',
  巳: 'sì|sixth Earthly Branch',
  巴: 'bā|to hope for; (used in names)',
  巷: 'xiàng|alley',
  巾: 'jīn|towel; cloth',
  市: 'shì|market; city',
  布: 'bù|cloth; to announce',
  帆: 'fān|sail',
  师: 'shī|teacher; master',
  希: 'xī|to hope; rare',
  帮: 'bāng|to help',
  常: 'cháng|often; ordinary',
  帽: 'mào|hat',
  平: 'píng|flat; peaceful; level',
  并: 'bìng|and; also; to combine',
  幸: 'xìng|fortunate',
  幼: 'yòu|young',
  幽: 'yōu|quiet; secluded',
  广: 'guǎng|wide; broad',
  庆: 'qìng|to celebrate',
  床: 'chuáng|bed',
  序: 'xù|order; sequence',
  库: 'kù|storehouse',
  应: 'yīng / yìng|should / to respond',
  店: 'diàn|shop; store',
  庙: 'miào|temple',
  府: 'fǔ|government office; mansion',
  度: 'dù|degree; to spend (time)',
  康: 'kāng|healthy',
  延: 'yán|to extend; to delay',
  建: 'jiàn|to build',
  廾: 'gǒng|two hands (radical)',
  异: 'yì|different',
  弃: 'qì|to abandon',
  式: 'shì|style; type; ceremony',
  弓: 'gōng|bow',
  引: 'yǐn|to lead; to attract',
  弗: 'fú|not (literary; component)',
  弟: 'dì|younger brother',
  弱: 'ruò|weak',
  弹: 'tán / dàn|to play (strings) / bullet',
  强: 'qiáng|strong',
  彑: 'jì|pig’s head (component)',
  录: 'lù|to record',
  彡: 'shān|hair; bristles (radical)',
  形: 'xíng|shape; form',
  彦: 'yàn|accomplished scholar (component)',
  影: 'yǐng|shadow; image; film',
  律: 'lǜ|law; rule',
  微: 'wēi|tiny; micro-',
  心: 'xīn|heart; mind',
  忄: 'xīn|heart — side form of 心 (radical)',
  必: 'bì|must; certainly',
  忆: 'yì|to recall',
  志: 'zhì|will; ambition',
  忘: 'wàng|to forget',
  忠: 'zhōng|loyal',
  念: 'niàn|to read aloud; to miss',
  忽: 'hū|suddenly',
  怀: 'huái|bosom; to cherish',
  态: 'tài|attitude; state',
  怎: 'zěn|how',
  怒: 'nù|anger',
  怕: 'pà|to fear',
  怜: 'lián|to pity',
  思: 'sī|to think',
  急: 'jí|urgent; anxious',
  性: 'xìng|nature; character; sex',
  怪: 'guài|strange; to blame',
  总: 'zǒng|always; total',
  恐: 'kǒng|to fear',
  恭: 'gōng|respectful',
  息: 'xī|breath; news; to rest',
  恼: 'nǎo|annoyed',
  悉: 'xī|to know (in 熟悉)',
  悔: 'huǐ|to regret',
  情: 'qíng|feeling; situation',
  惊: 'jīng|to startle; surprised',
  惜: 'xī|to cherish; pity',
  惯: 'guàn|habit; used to',
  愉: 'yú|pleasant; happy',
  意: 'yì|meaning; idea; wish',
  感: 'gǎn|to feel',
  愿: 'yuàn|to wish; willing',
  慕: 'mù|to admire',
  戈: 'gē|dagger-axe (radical)',
  戊: 'wù|fifth Heavenly Stem',
  戏: 'xì|play; drama',
  成: 'chéng|to become; to succeed',
  或: 'huò|or',
  戚: 'qī|relative',
  户: 'hù|door; household',
  房: 'fáng|house; room',
  所: 'suǒ|place; that which',
  扁: 'biǎn|flat',
  手: 'shǒu|hand',
  扌: 'shǒu|hand — side form of 手 (radical)',
  打: 'dǎ|to hit; to play',
  执: 'zhí|to hold; to carry out',
  扫: 'sǎo|to sweep',
  扬: 'yáng|to raise; to spread',
  扮: 'bàn|to dress up as',
  扰: 'rǎo|to disturb',
  批: 'pī|to criticize; batch',
  技: 'jì|skill',
  折: 'zhé|to fold; to break; discount',
  护: 'hù|to protect',
  报: 'bào|newspaper; to report',
  抽: 'chōu|to draw out; to smoke',
  担: 'dān|to carry; to take on',
  拐: 'guǎi|to turn; to kidnap',
  拒: 'jù|to refuse',
  招: 'zhāo|to beckon; to recruit',
  拜: 'bài|to pay respects; to visit',
  择: 'zé|to choose',
  拾: 'shí|to pick up',
  持: 'chí|to hold',
  按: 'àn|to press; according to',
  据: 'jù|according to; evidence',
  授: 'shòu|to teach; to award',
  掌: 'zhǎng|palm; to control',
  排: 'pái|row; to line up',
  握: 'wò|to grasp',
  播: 'bō|to broadcast; to sow',
  支: 'zhī|to support; branch',
  攵: 'pū|to tap; action (side radical)',
  攸: 'yōu|distant (component)',
  改: 'gǎi|to change; to correct',
  故: 'gù|old; reason; therefore',
  效: 'xiào|effect',
  救: 'jiù|to save; to rescue',
  散: 'sàn|to scatter',
  数: 'shù / shǔ|number / to count',
  整: 'zhěng|whole; to tidy',
  文: 'wén|writing; culture; language',
  料: 'liào|material; to expect',
  斤: 'jīn|half a kilogram; axe',
  断: 'duàn|to break; to cut off',
  方: 'fāng|square; direction; method',
  施: 'shī|to carry out; to give',
  旁: 'páng|side; beside',
  旅: 'lǚ|to travel',
  族: 'zú|ethnic group; clan',
  旡: 'jì|to choke (component)',
  既: 'jì|since; already',
  旦: 'dàn|dawn',
  早: 'zǎo|early; morning',
  时: 'shí|time; hour',
  昆: 'kūn|elder brother; insect (昆虫)',
  昌: 'chāng|prosperous',
  明: 'míng|bright; clear; next (明天)',
  昏: 'hūn|dusk; confused',
  易: 'yì|easy; to change',
  昔: 'xī|former times',
  星: 'xīng|star',
  映: 'yìng|to reflect; to show',
  昨: 'zuó|yesterday',
  昷: 'wēn|warm (component)',
  晓: 'xiǎo|dawn; to know',
  晚: 'wǎn|evening; late',
  普: 'pǔ|general; universal',
  暂: 'zàn|temporary',
  暑: 'shǔ|summer heat',
  暖: 'nuǎn|warm',
  曷: 'hé|why (component)',
  曹: 'cáo|surname Cao',
  曼: 'màn|graceful; prolonged',
  替: 'tì|to replace; for',
  最: 'zuì|most',
  朋: 'péng|friend',
  服: 'fú|clothes; to serve; to obey',
  望: 'wàng|to look at; to hope',
  期: 'qī|period; to expect',
  木: 'mù|tree; wood',
  未: 'wèi|not yet',
  末: 'mò|end; tip',
  术: 'shù|skill; art',
  朵: 'duǒ|measure word for flowers, clouds',
  机: 'jī|machine; opportunity',
  杂: 'zá|mixed; miscellaneous',
  李: 'lǐ|plum; surname Li',
  材: 'cái|material',
  束: 'shù|bundle; to bind',
  杯: 'bēi|cup',
  松: 'sōng|pine; loose',
  板: 'bǎn|board',
  林: 'lín|forest; woods',
  果: 'guǒ|fruit; result',
  染: 'rǎn|to dye; to infect',
  查: 'chá|to check',
  标: 'biāo|mark; sign',
  校: 'xiào|school',
  样: 'yàng|kind; appearance',
  根: 'gēn|root',
  格: 'gé|pattern; grid',
  案: 'àn|case; table',
  桌: 'zhuō|table; desk',
  桶: 'tǒng|bucket',
  梅: 'méi|plum blossom',
  梨: 'lí|pear',
  梯: 'tī|ladder; stairs',
  检: 'jiǎn|to inspect',
  森: 'sēn|forest',
  椅: 'yǐ|chair',
  植: 'zhí|to plant',
  楚: 'chǔ|clear (in 清楚)',
  概: 'gài|general; approximate',
  模: 'mó|model; pattern',
  橡: 'xiàng|oak; rubber (橡皮 eraser)',
  欠: 'qiàn|to owe; to lack',
  欢: 'huān|joyful',
  款: 'kuǎn|sum of money; style',
  歉: 'qiàn|apology',
  歌: 'gē|song',
  止: 'zhǐ|to stop',
  正: 'zhèng|correct; just (now)',
  此: 'cǐ|this',
  步: 'bù|step',
  殳: 'shū|weapon (radical)',
  母: 'mǔ|mother',
  毕: 'bì|to finish',
  氏: 'shì|clan; surname',
  氐: 'dī|base (component)',
  民: 'mín|people',
  气: 'qì|air; gas; anger',
  氵: 'shuǐ|water — side form of 水 (radical)',
  永: 'yǒng|forever',
  汁: 'zhī|juice',
  求: 'qiú|to request; to seek',
  汉: 'hàn|Han Chinese',
  江: 'jiāng|river',
  污: 'wū|dirty; to pollute',
  汽: 'qì|steam',
  沙: 'shā|sand',
  河: 'hé|river',
  油: 'yóu|oil',
  泉: 'quán|spring (water)',
  法: 'fǎ|law; method',
  波: 'bō|wave',
  注: 'zhù|to pour; to note',
  泳: 'yǒng|to swim',
  泼: 'pō|to splash',
  洋: 'yáng|ocean; foreign',
  洲: 'zhōu|continent',
  活: 'huó|to live; alive',
  派: 'pài|to send; faction',
  流: 'liú|to flow',
  测: 'cè|to measure',
  济: 'jì|to aid (in 经济 economy)',
  浪: 'làng|wave; wasteful',
  海: 'hǎi|sea',
  消: 'xiāo|to disappear; to eliminate',
  混: 'hùn|to mix',
  清: 'qīng|clear; clean',
  温: 'wēn|warm; temperature',
  港: 'gǎng|harbor',
  游: 'yóu|to swim; to travel',
  湖: 'hú|lake',
  漂: 'piào / piāo|pretty (漂亮) / to float',
  演: 'yǎn|to perform',
  漫: 'màn|to overflow; free',
  澡: 'zǎo|bath (洗澡)',
  激: 'jī|to excite; fierce',
  灬: 'huǒ|fire — bottom form of 火 (radical)',
  灾: 'zāi|disaster',
  炎: 'yán|flame; inflammation',
  炒: 'chǎo|to stir-fry',
  炼: 'liàn|to refine',
  烝: 'zhēng|to steam (component)',
  烟: 'yān|smoke; cigarette',
  烤: 'kǎo|to roast; to bake',
  烦: 'fán|annoyed; troubled',
  烧: 'shāo|to burn; to cook',
  然: 'rán|so; like this',
  熊: 'xióng|bear',
  熟: 'shú|ripe; familiar',
  爫: 'zhǎo|claw — top form of 爪 (radical)',
  爬: 'pá|to climb; to crawl',
  爰: 'yuán|thereupon (component)',
  父: 'fù|father',
  爷: 'yé|grandpa',
  爸: 'bà|dad',
  爹: 'diē|dad (colloquial)',
  片: 'piàn|slice; piece',
  牌: 'pái|sign; brand; card',
  牙: 'yá|tooth',
  牛: 'niú|cow; ox',
  物: 'wù|thing; object',
  特: 'tè|special',
  犬: 'quǎn|dog',
  犭: 'quǎn|dog / animal — side form of 犬 (radical)',
  玉: 'yù|jade',
  王: 'wáng|king',
  环: 'huán|ring; to surround',
  现: 'xiàn|present; to appear',
  球: 'qiú|ball',
  理: 'lǐ|reason; to manage',
  琴: 'qín|stringed instrument',
  瓜: 'guā|melon',
  瓶: 'píng|bottle',
  甚: 'shèn|very; extremely',
  生: 'shēng|to be born; life; raw',
  甫: 'fǔ|just; only (component)',
  甬: 'yǒng|path (component)',
  田: 'tián|field',
  甲: 'jiǎ|first; armor',
  申: 'shēn|to state; to apply',
  电: 'diàn|electricity',
  界: 'jiè|boundary; world',
  番: 'fān|time; turn; foreign',
  疋: 'pǐ|bolt of cloth (radical)',
  疑: 'yí|to doubt',
  病: 'bìng|illness',
  痛: 'tòng|pain',
  登: 'dēng|to climb; to board',
  皮: 'pí|skin; leather',
  监: 'jiān|to supervise',
  盒: 'hé|box',
  盘: 'pán|plate; tray',
  目: 'mù|eye',
  直: 'zhí|straight; directly',
  相: 'xiāng / xiàng|each other / appearance',
  眼: 'yǎn|eye',
  睛: 'jīng|eyeball (眼睛)',
  睡: 'shuì|to sleep',
  知: 'zhī|to know',
  矿: 'kuàng|mine; mineral',
  码: 'mǎ|code; number',
  研: 'yán|to research',
  础: 'chǔ|foundation (基础)',
  硕: 'shuò|large (硕士 master’s degree)',
  确: 'què|true; certain',
  示: 'shì|to show',
  礻: 'shì|spirit — side form of 示 (radical)',
  礼: 'lǐ|ceremony; gift; manners',
  社: 'shè|society; organization',
  祝: 'zhù|to wish; to express good wishes',
  神: 'shén|god; spirit',
  禁: 'jìn|to prohibit',
  福: 'fú|good fortune',
  禺: 'yù|monkey (component)',
  秀: 'xiù|elegant; excellent',
  科: 'kē|subject; branch of study',
  积: 'jī|to accumulate',
  程: 'chéng|procedure; journey',
  稍: 'shāo|slightly',
  究: 'jiū|to investigate',
  突: 'tū|sudden; to protrude',
  窗: 'chuāng|window',
  立: 'lì|to stand',
  竞: 'jìng|to compete',
  竟: 'jìng|unexpectedly',
  章: 'zhāng|chapter; seal',
  童: 'tóng|child',
  端: 'duān|end; to carry',
  竹: 'zhú|bamboo',
  笔: 'bǐ|pen',
  符: 'fú|symbol; to match',
  第: 'dì|ordinal prefix (first, second…)',
  答: 'dá|to answer',
  策: 'cè|plan; policy',
  筷: 'kuài|chopsticks',
  签: 'qiān|to sign; label',
  简: 'jiǎn|simple',
  算: 'suàn|to calculate',
  管: 'guǎn|to manage; tube',
  箱: 'xiāng|box; case',
  篮: 'lán|basket',
  粉: 'fěn|powder; pink',
  粗: 'cū|thick; rough',
  粽: 'zòng|zongzi (rice dumpling)',
  糕: 'gāo|cake',
  系: 'xì|system; department; to tie',
  紧: 'jǐn|tight; urgent',
  约: 'yuē|appointment; about',
  级: 'jí|level; grade',
  纟: 'sī|silk — side form of 糸 (radical)',
  纪: 'jì|record; discipline',
  纳: 'nà|to receive; to accept',
  纸: 'zhǐ|paper',
  线: 'xiàn|line; thread',
  练: 'liàn|to practice',
  组: 'zǔ|group; to form',
  细: 'xì|thin; fine; careful',
  织: 'zhī|to weave',
  终: 'zhōng|end; finally',
  绍: 'shào|to continue (in 介绍)',
  经: 'jīng|to pass through; classic',
  结: 'jié|to tie; to conclude',
  绝: 'jué|absolutely; to cut off',
  统: 'tǒng|to unite; system',
  继: 'jì|to continue',
  绩: 'jì|achievement',
  续: 'xù|to continue',
  维: 'wéi|to maintain',
  缺: 'quē|to lack',
  网: 'wǎng|net; internet',
  罗: 'luó|net; (transliteration)',
  羊: 'yáng|sheep',
  美: 'měi|beautiful; America',
  羞: 'xiū|shy',
  羡: 'xiàn|to envy',
  羽: 'yǔ|feather',
  翅: 'chì|wing',
  翻: 'fān|to turn over; to translate',
  考: 'kǎo|to test',
  者: 'zhě|one who… (-er)',
  耐: 'nài|to endure',
  耳: 'ěr|ear',
  聊: 'liáo|to chat',
  职: 'zhí|job; duty',
  联: 'lián|to unite; to connect',
  聘: 'pìn|to hire',
  聚: 'jù|to gather',
  聪: 'cōng|clever',
  肉: 'ròu|meat',
  肌: 'jī|muscle',
  肚: 'dù|belly',
  肤: 'fū|skin',
  肥: 'féi|fat',
  肯: 'kěn|willing',
  育: 'yù|to raise; education',
  胡: 'hú|beard; reckless',
  胳: 'gē|arm (胳膊)',
  脑: 'nǎo|brain',
  脾: 'pí|spleen; temper (脾气)',
  膊: 'bó|arm (胳膊)',
  膏: 'gāo|paste; ointment',
  自: 'zì|self; from',
  至: 'zhì|to arrive; most',
  舌: 'shé|tongue',
  舒: 'shū|to relax; comfortable',
  舞: 'wǔ|to dance',
  航: 'háng|to navigate; to fly',
  般: 'bān|sort; kind',
  艮: 'gèn|tough; stopping (component)',
  色: 'sè|color',
  艹: 'cǎo|grass — top form of 艸 (radical)',
  艺: 'yì|art; skill',
  英: 'yīng|hero; England',
  苹: 'píng|apple (苹果)',
  范: 'fàn|model; pattern',
  荐: 'jiàn|to recommend',
  荣: 'róng|glory',
  荧: 'yíng|glimmer',
  荷: 'hé|lotus',
  莫: 'mò|do not',
  获: 'huò|to obtain',
  落: 'luò|to fall',
  著: 'zhù|famous; to write',
  董: 'dǒng|director',
  蒸: 'zhēng|to steam',
  蕉: 'jiāo|banana (香蕉)',
  虎: 'hǔ|tiger',
  虑: 'lǜ|to consider',
  虫: 'chóng|insect',
  虽: 'suī|although',
  虾: 'xiā|shrimp',
  蚁: 'yǐ|ant',
  蛇: 'shé|snake',
  蛋: 'dàn|egg',
  蜘: 'zhī|spider (蜘蛛)',
  行: 'xíng / háng|to walk; OK / row; profession',
  街: 'jiē|street',
  衣: 'yī|clothes',
  衤: 'yī|clothing — side form of 衣 (radical)',
  表: 'biǎo|surface; watch; to show',
  衫: 'shān|shirt',
  衬: 'chèn|lining (衬衫 shirt)',
  袋: 'dài|bag',
  袜: 'wà|socks',
  裙: 'qún|skirt',
  裤: 'kù|pants',
  见: 'jiàn|to see',
  观: 'guān|to watch; view',
  规: 'guī|rule',
  视: 'shì|to look at',
  觉: 'jué / jiào|to feel / sleep',
  解: 'jiě|to untie; to explain',
  言: 'yán|speech; words',
  警: 'jǐng|to warn; police',
  讠: 'yán|speech — side form of 言 (radical)',
  计: 'jì|to count; plan',
  订: 'dìng|to book; to order',
  认: 'rèn|to recognize',
  讨: 'tǎo|to discuss; to ask for',
  议: 'yì|to discuss',
  记: 'jì|to remember; to record',
  许: 'xǔ|to allow; perhaps',
  论: 'lùn|to discuss; theory',
  访: 'fǎng|to visit',
  证: 'zhèng|proof; certificate',
  评: 'píng|to comment; to judge',
  识: 'shí|to know',
  诉: 'sù|to tell',
  词: 'cí|word',
  译: 'yì|to translate',
  诗: 'shī|poem',
  诚: 'chéng|sincere',
  话: 'huà|speech; words',
  该: 'gāi|should',
  详: 'xiáng|detailed',
  语: 'yǔ|language',
  误: 'wù|mistake',
  调: 'tiáo / diào|to adjust / tone; to transfer',
  谅: 'liàng|to forgive',
  谈: 'tán|to talk',
  谊: 'yì|friendship',
  谢: 'xiè|to thank',
  谨: 'jǐn|cautious',
  谷: 'gǔ|valley; grain',
  豕: 'shǐ|pig (radical)',
  象: 'xiàng|elephant; image',
  貌: 'mào|appearance',
  贝: 'bèi|shell — money (radical)',
  负: 'fù|to bear; negative',
  财: 'cái|wealth',
  责: 'zé|duty; to blame',
  败: 'bài|to fail; to defeat',
  货: 'huò|goods',
  质: 'zhì|quality; nature',
  贫: 'pín|poor',
  购: 'gòu|to buy',
  贯: 'guàn|to pierce through',
  贷: 'dài|loan',
  费: 'fèi|fee; to spend',
  贺: 'hè|to congratulate',
  资: 'zī|resources; capital',
  赛: 'sài|competition',
  赞: 'zàn|to praise',
  起: 'qǐ|to rise; to start',
  超: 'chāo|to exceed; super',
  趣: 'qù|interest; fun',
  足: 'zú|foot; enough',
  跑: 'pǎo|to run',
  距: 'jù|distance',
  跳: 'tiào|to jump',
  踢: 'tī|to kick',
  身: 'shēn|body',
  车: 'chē|vehicle; car',
  轮: 'lún|wheel; turn',
  软: 'ruǎn|soft',
  较: 'jiào|relatively; to compare',
  辅: 'fǔ|to assist',
  辛: 'xīn|bitter; hard work',
  辰: 'chén|morning; fifth Earthly Branch',
  辶: 'chuò|walk / movement (radical)',
  边: 'biān|side; edge',
  达: 'dá|to reach',
  迎: 'yíng|to welcome',
  运: 'yùn|to transport; luck',
  迟: 'chí|late',
  迷: 'mí|lost; fan (of)',
  退: 'tuì|to retreat; to return (goods)',
  适: 'shì|suitable',
  逃: 'táo|to escape',
  选: 'xuǎn|to choose',
  透: 'tòu|to penetrate; thoroughly',
  通: 'tōng|to go through; to connect',
  速: 'sù|speed',
  遇: 'yù|to meet',
  道: 'dào|road; way; to say',
  遗: 'yí|to lose; to leave behind',
  邀: 'yāo|to invite',
  邮: 'yóu|post; mail',
  邻: 'lín|neighbor',
  郊: 'jiāo|suburbs',
  部: 'bù|part; department',
  酉: 'yǒu|wine vessel (radical)',
  酒: 'jiǔ|alcohol; wine',
  醒: 'xǐng|to wake up',
  釆: 'biàn|to distinguish (radical)',
  采: 'cǎi|to pick; to gather',
  释: 'shì|to explain',
  量: 'liàng / liáng|quantity / to measure',
  金: 'jīn|gold; metal',
  钅: 'jīn|metal — side form of 金 (radical)',
  针: 'zhēn|needle',
  钟: 'zhōng|clock; bell',
  钢: 'gāng|steel',
  钥: 'yào|key (钥匙)',
  铁: 'tiě|iron',
  铅: 'qiān|lead (metal)',
  银: 'yín|silver',
  锁: 'suǒ|lock',
  锅: 'guō|pot; wok',
  锋: 'fēng|sharp edge',
  键: 'jiàn|key (on a keyboard)',
  锻: 'duàn|to forge (锻炼 to exercise)',
  镜: 'jìng|mirror; lens',
  闭: 'bì|to close',
  间: 'jiān|between; room',
  闹: 'nào|noisy',
  闻: 'wén|to hear; to smell',
  阅: 'yuè|to read',
  阜: 'fù|mound (radical)',
  阝: 'fù / yì|mound (left side) / city (right side) — radical form',
  队: 'duì|team; line',
  阳: 'yáng|sun; positive',
  阴: 'yīn|cloudy; negative',
  阶: 'jiē|stairs; rank',
  阿: 'ā|prefix (e.g. 阿姨)',
  附: 'fù|to attach; nearby',
  际: 'jì|border; between',
  降: 'jiàng|to fall; to lower',
  院: 'yuàn|courtyard; institution',
  除: 'chú|to remove; except',
  险: 'xiǎn|danger',
  随: 'suí|to follow',
  隹: 'zhuī|short-tailed bird (radical)',
  雇: 'gù|to hire',
  雨: 'yǔ|rain',
  雷: 'léi|thunder',
  需: 'xū|to need',
  震: 'zhèn|to shake; earthquake',
  青: 'qīng|blue-green; young',
  静: 'jìng|quiet',
  非: 'fēi|not; wrong',
  面: 'miàn|face; surface; noodles',
  音: 'yīn|sound',
  顶: 'dǐng|top; to push up',
  项: 'xiàng|item',
  顺: 'shùn|smooth; along',
  须: 'xū|must',
  顾: 'gù|to look after',
  预: 'yù|in advance',
  颜: 'yán|face; color',
  风: 'fēng|wind',
  飞: 'fēi|to fly',
  餐: 'cān|meal',
  饣: 'shí|food — side form of 食 (radical)',
  饭: 'fàn|cooked rice; meal',
  饮: 'yǐn|to drink',
  饺: 'jiǎo|dumpling',
  饼: 'bǐng|flatbread; cake',
  馆: 'guǎn|building; hall',
  首: 'shǒu|head; first',
  驾: 'jià|to drive',
  骂: 'mà|to scold',
  骄: 'jiāo|proud',
  验: 'yàn|to test',
  鲜: 'xiān|fresh',
  鸡: 'jī|chicken',
  鸭: 'yā|duck',
  麻: 'má|hemp; numb',
  黄: 'huáng|yellow',
  默: 'mò|silent',
  鼓: 'gǔ|drum',
  鼻: 'bí|nose',
  龄: 'líng|age',
};

export function parseGloss(raw: string): { pinyin: string; meaning: string } {
  const i = raw.indexOf('|');
  return i === -1
    ? { pinyin: '', meaning: raw }
    : { pinyin: raw.slice(0, i), meaning: raw.slice(i + 1) };
}
